### ISSUE TITLE
Device (dlq) not showing in Accesories, but detected in log and works in Tuya IoT Platform

### ISSUE THREAD

**Issue by DanAykroyd256** [tuya/tuya-homebridge#208]
**Describe the bug**
I own only one device in my Tuya account, a breaker, that shows up correctly in the Tuya IoT Platform development project, I can go to the “Debug” tab there and I'm able to reach the device and send commands to it from the Tuya IoT Platform and they work perfectly.

In Homebridge, with this plug-in, I see it detected during the startup log. It discovers its name, attributes, commands, but doesn't show the device in the “Accesories” tab

**Expected behavior**
I expect the device to show up in Accesories as a switch, in order to be able to turn it on/off, the same way it works fine from the debug tab in Tuya IoT Platform

**Screenshots**
It works great form the Debug tab in the Tuya IoT Platform. It show these values as available and it would be expected to get the “switch” value in accesories / HomeKit to be able to turn on/off the device; the same way it works from the Debug tab there
![image](https://user-images.githubusercontent.com/64184474/150487149-b4ddce57-978b-404f-81ae-01d2d911dc75.png)

**Device info**
{
   "active_time":1642750341,
   "biz_type":0,
   "category":"dlq",
   "create_time":1642750341,
   "icon":"smart/icon/bay1591839287906taVN/073f2e2ff5f3c3c3b62c096c74145863.png",
   "id":"<REDACTED>”,
   "ip":"<REDACTED>",
   "lat":"<REDACTED>",
   "local_key":"<REDACTED>",
   "lon":"<REDACTED>",
   "model":"",
   "name":"Breaker ",
   "online":true,
   "owner_id":"<REDACTED>",
   "product_id":"<REDACTED>",
   "product_name":"电源保护器",
   "status":[
      {
         "code":"total_forward_energy",
         "value":0
      },
      {
         "code":"phase_a",
         "value":"CKwAAAAAAAAAAA=="
      },
      {
         "code":"phase_b",
         "value":"AAAAAAAAAAAAAA=="
      },
      {
         "code":"phase_c",
         "value":"AAAAAAAAAAAAAA=="
      },
      {
         "code":"fault",
         "value":0
      },
      {
         "code":"switch_prepayment",
         "value":false
      },
      {
         "code":"energy_reset",
         "value":"empty"
      },
      {
         "code":"balance_energy",
         "value":0
      },
      {
         "code":"charge_energy",
         "value":0
      },
      **{
         "code":"switch",
         "value":false
      },**
      {
         "code":"breaker_number",
         "value":"<REDACTED>"
      }
   ],
   "sub":false,
   "time_zone":"<REDACTED>",
   "uid":"<REDACTED>",
   "update_time":1642750346,
   "uuid":"<REDACTED>"
}

**Device functions**
{
   "code":"switch_prepayment",
   "desc":"switch prepayment",
   "name":"switch prepayment",
   "type":"Boolean",
   "values":"{}"
},
{
   "code":"energy_reset",
   "desc":"energy reset",
   "name":"energy reset",
   "type":"Enum",
   "values":"{\"range\":[\"empty\"]}"
},
{
   "code":"charge_energy",
   "desc":"charge energy",
   "name":"charge energy",
   "type":"Integer",
   "values":"{\"unit\":\"kW·h\",\"min\":0,\"max\":999999,\"scale\":2,\"step\":1}"
},
**{
   "code":"switch",
   "desc":"switch",
   "name":"switch",
   "type":"Boolean",
   "values":"{}"
}**

**Comment by Vasco203** [comment]
Hello,

I have exactly the same issue. How can it be fixed?
I see the clkg in the IoT page, in the Tuya app and it works both. It also shows up in the log in Hoobs but doesn't shows up in the accessories page.

Any help would be much appreciated.
Thanks!

Vasco

**Comment by DanAykroyd256** [comment]
The awesome talrhv added these devices in [his fork](https://github.com/tuya/tuya-homebridge/issues/166)! Could you please update this main one to support those too?

Thanks.

**Comment by DanAykroyd256** [comment]
> Thank you for your feedback, we will solve this issue soon

Any updates?

**Comment by gregconnors** [comment]
Hello. 
I, too, have the same issue. Although it is with a ceiling fan with LED light (which I assume are supported devices)

I see the device in the Homebridge logs and every command I send (either by the physical remote, Tuya Smart app or Tuya web IoT Device Debugging) is logged correctly.

The device is not shown in Homebridge accessories panel. I'm wondering/hoping if this will be shown as two devices (one for the fan and one for the LED light)

I have also created a new instance of Homebridge to bridge to Home app and issue remains. (I did this because if I followed the YouTube installation video it says to pair Homebridge to Home and I get a message saying already paired and need to reset which I didn't want to do because I would lose all current Homebridge accessories. And I wondered if a clean install would resolve issue.)

I assume the Tuya plug-in is supposed to populate the accessories and there is no need to create accessories in the config file. Additionally, using the Homebridge UI settings dialog box for plugin the endpoint parameter was not shown, so I entered that manually in the config file.

I've been struggling with this plug in for many months. I'm hesitant to purchase other Tuya based products until I can resolve this one.

Thanks, Greg.

**Comment by DanAykroyd256** [comment]
Hi @gregconnors,

From what I have gathered these past few months here, if your device shows up in the boot-up log in Homebridge, they could “easily” add it to a some kind of whitelist that they have in the code (I don't know what it is, exactly), where they add the device and it shows in accesories; as most of the work is already done.

But sadly, I don't think they are supporting this plug-in very much (if at all), as I see a lot of these issues opened, with the automatic response of “This will be fixed soon"

**Comment by gregconnors** [comment]
Thanks for the response @DanAykroyd256. Sadly, I agree with you regarding ongoing development/support. 

Maybe Matter will make a difference, although I don't hold out hope that most things like ceiling fans will get firmware upgrades (they'll want to get us to pay for new models).

**Comment by andre4nap** [comment]
after more than a year and a half the problem is still present. is there any possibility of resolution?
