### ISSUE TITLE
Power Strip won't appear in Home app

### ISSUE THREAD

**Issue by bosco90** [tuya/tuya-homebridge#33]
Hi,
as briefly said in #2 the power strip doesn't appear in the Home app.

The logs says the following for both of them:

Adding: Presa bagno (**pc** / 6715286024a160171693)

and for the same productKey, in the "TuyaOpenMQ" section, it says "Could not find accessory in dictionary" multiple times.
Maybe they were added as a wrong type?

Thanks.

**Comment by Hanh94** [comment]
Hi @bosco90 , https://github.com/tuya/tuya-homebridge/issues/2#issuecomment-857638089
As [](https://github.com/tuya/tuya-homebridge/issues/2#issuecomment-857638089) says here, we currently support "cz", but not yet supported "pc", so "pc" will not be created at creation of accessory. **"Could not find accessory in dictionary"** is because the callback message of MQTT on "pc" device did not find the corresponding accessory, which in fact does not affect the use of your other devices. Sorry for the misunderstanding caused by this log. We will be managing this log and will soon support the "pc" category.

**Comment by bosco90** [comment]
Good! So it will be supported on a future update :D I look forward to it.

Thanks ;)

**Comment by Hanh94** [comment]
Hi @bosco90 , We support "pc" in the latest version, please update and try again.

**Comment by bosco90** [comment]
It wooorks!!! You made me so happy 😁 thank you!!!
