### ISSUE TITLE
Tuya Strip Light (Product ID: vnroaagz68oeftni) cannot be added to home app

### ISSUE THREAD

**Issue by asifrhm** [tuya/tuya-homebridge#66]
The Strip light cannot  be added to the home app.

Product ID: vnroaagz68oeftni

**Comment by Hanh94** [comment]
Hi @asifrhm , Thank you for your feedback.
Please submit an Issue in the Issue Template format so that we can better help you solve the issue.
your device category should be **"dd"**, because this category is not in the Tuya standard instruction set. We will support it in the next version as soon as possible. Please refer to [more information](https://github.com/tuya/tuya-homebridge/wiki/Supported-Tuya-Device-Types) of the supported category.

**Comment by Hanh94** [comment]
https://github.com/tuya/tuya-homebridge/issues/60

**Comment by asifrhm** [comment]
Hi @Hanh94,

What is the template format? 

Also, How can I find the device category of the Tuya device
![Capture](https://user-images.githubusercontent.com/87333388/125406969-16c37180-e3c2-11eb-9e9b-71a6c8106d49.PNG)

**Comment by Hanh94** [comment]
https://github.com/tuya/tuya-homebridge/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by Hanh94** [comment]
Hi @asifrhm ,We already support Category "dd "in version 1.3.0, please update and try again.

**Comment by asifrhm** [comment]
yes its working now, thanks
