### ISSUE TITLE
Subscription plans?

### ISSUE THREAD

**Issue by alxalxnet** [tuya/tuya-homebridge#7]
I noticed that I need to subscribe a plan in order to create a project and set-up this plug-in. Since even the free option is just a trial, is it correct to assume that this plug-in is not free?

**Comment by zlinoliver** [comment]
Hi @alxalxnet , the trial edition is **free** with only 1 project and 50 devices limitation, about 30 thousand API calls plus 80 thousand message subscriptions per month. For more info, please check the [pricing doc](https://developer.tuya.com/en/docs/iot/membership-service?id=K9m8k45jwvg9j).

Also, for the **basic edition** of Cloud API Products in Tuya IoT Platform, it has 1 year **validity period**, but you can renew it for free once it's expired. We will consider to remove this 1 year validity period for basic edition setting too. 

Hope this info helps!

**Comment by rcoletti116** [comment]
I'm pretty sure from reading all the documentation and signing up myself that this eventually will not be free. If you are a user on the trial, what happens to this plugin if you are using it after the trial ends? I think it will stop working because the APIs will stop responding. Please clarify if this is case.

**Comment by codyc1515** [comment]
The best way to sort this would be for Tuya themselves to provide us some kind of generic credentials and then handle the subscription stuff themselves, unless they would eventually intend to charge.

**Comment by Hanh94** [comment]
Hi guys, The cost of plugin is explained [here](https://github.com/tuya/tuya-homebridge#faq), We will close this issue first. If you have any questions, please contact us at any time.

**Comment by mikagorka** [comment]
According to the information provided on the page: [Pricing](https://developer.tuya.com/en/docs/iot/membership-service?id=K9m8k45jwvg9j)
> The Trial Edition only applies to individual developers or works for debugging purposes. Commercial use is prohibited.

The trial edition has a limited monthly allowance for API calls and messages. Once that allowance is reached, the service will be suspended until the allowance is refreshed next month. However, since the trial edition is not intended for ongoing commercial use, it cannot be renewed or continued after the initial one month period expires. So the trial version would no longer be usable after one month.
